version: '3.4'

services:
  dbserver:
    image: microsoft/mssql-server-linux:2017-latest  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "D0ckerOnlyClowns!"
    volumes:  
      - mssqlsystem:/var/opt/mssql/ 
      - mssqluser:/var/opt/sqlserver 
    ports:  
      - '1433:1433'  
volumes:
  mssqlsystem: 
  mssqluser: